#!/usr/bin/perl
##################################################
# LiteSpeed webserver : connections
##################################################
if ( $ARGV[0] eq 'autoconf' ) {
   if ( -e '/tmp/lshttpd/.rtreport' ) {
      print "yes\n";
      exit;
   } else {
      print "no\n";
      exit 1;
   }
}

if ( $ARGV[0] eq 'config' ) {
   open IN, "</tmp/lshttpd/.rtreport";
   while ( <IN> ) {
      if ( /^MAXCONN: (\d+),/ ) {
         $max = $1;
         last;
      }
   }
   close IN;
   print "graph_title Litespeed : connections (max. $max)\n";
   print "graph_args --base 1000 -l 0\n";
   print "graph_scale no\n";
   print "graph_vlabel connections\n";
   print "graph_category litespeed\n";
   print "graph_order used idle\n";
   print "used.label used\n";
   print "used.draw AREA\n";
   print "used.colour 96E78A\n";
   print "idle.label idle\n";
   print "idle.draw LINE1\n";
   print "idle.colour 5C6CAE\n";
   exit 0;
}

if ( ! -e '/tmp/lshttpd/.rtreport' ) {
   print "used.value 0\n";
   print "idle.value 0\n";
   exit;
}

@stats = `ls -a /tmp/lshttpd/.rtreport*`;
foreach $rep ( @stats ) {
   open IN, "<$rep";
   while ( <IN> ) {
      if ( /PLAINCONN: (\d+), AVAILCONN: \d+, IDLECONN: (\d+),/ ) {
         $used += $1;
         $idle += $2;
         last;
      }
   }
   close IN;
}
print "used.value $used\nidle.value $idle\n";
exit;
