#!/usr/bin/perl
##################################################
# LiteSpeed webserver : number of requests
##################################################
if ( $ARGV[0] eq 'autoconf' ) {
   if ( -e '/tmp/lshttpd/.rtreport' ) {
      print "yes\n";
      exit;
   } else {
      print "no\n";
      exit 1;
   }
}

if ( $ARGV[0] eq 'config' ) {
   print "graph_title Litespeed : requests\n";
   print "graph_args --base 1000 -l 0\n";
   print "graph_scale no\n";
   print "graph_vlabel requests\n";
   print "graph_category litespeed\n";
   print "rqip.label ReqInProcess\n";
   print "rqip.draw AREA\n";
   print "rqip.colour 96E78A\n";
   print "rqps.label ReqPerSecond\n";
   print "rqps.draw LINE1\n";
   print "rqps.colour 5C6CAE\n";
   exit 0;
}

if ( ! -e '/tmp/lshttpd/.rtreport' ) {
   print "rqip.value 0\n";
   print "rqps.value 0\n";
   exit 0;
}

@stats = `ls -a /tmp/lshttpd/.rtreport*`;
foreach $rep ( @stats ) {
   open IN, "<$rep";
   while ( <IN> ) {
      if ( /REQ_PROCESSING: (\d+), REQ_PER_SEC: ([0-9]*\.?[0-9]+), TOT_REQS: / ) {
         $rqip += $1;
         $rqps += $2;
         last;
      }
   }
   close IN;
}
print "rqip.value $rqip\nrqps.value $rqps\n";
exit;
